### ISSUE TITLE
虎扑信息流广告误触

### ISSUE THREAD

**Issue by Chorson** [ganlinte/GKD-subscription#119]
### 请输入 误触/不执行规则 的界面的快照或者生成的快照链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

[虎扑_MainActivity-1734064264948.zip](https://github.com/user-attachments/files/18121343/_MainActivity-1734064264948.zip)

**Comment by ganlinte** [comment]
commit https://github.com/ganlinte/GKD-subscription/commit/ffda41dfed88209bac1554895a15606bbacd609c
