### ISSUE TITLE
npmmirror 订阅挂了

### ISSUE THREAD

**Issue by sheng-ri** [ganlinte/GKD-subscription#27]
### 请输入 误触/不执行规则 的界面的快照或者生成的快照链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

如题

**Comment by ganlinte** [comment]
npmmirror只同步了版本号，文件还没同步过去，不知道什么时候能同步

**Comment by ganlinte** [comment]
npmmirror新加了白名单机制，导致文件不通过

**Comment by ganlinte** [comment]
npmmirror链接已修复
