### ISSUE TITLE
。。。 有个规则好像出问题了

### ISSUE THREAD

**Issue by 1919114514** [ganlinte/GKD-subscription#49]
### 请输入 误触/不执行规则 的界面的快照或者生成的快照链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

![Screenshot_2024-07-06-17-23-00-283_li songe gkd](https://github.com/ganlinte/GKD-subscription/assets/154675691/82d95f40-5345-41b7-bff8-883d7a5512ec)

**Comment by ganlinte** [comment]
经过测试所有的导入链接均正常，测试gkd版本为1.7.3，规则最新版本为v20，新版本更改过规则框架，可能不兼容旧版本，可以删除规则重新导入，四个链接导入均为最新版v20，jsdelivr可能同步最新版较慢，Github或Github镜像可能需要挂梯子，npm镜像较为稳定。版本更新链接改为了导入是选择的网址
