### ISSUE TITLE
七猫全屏广告需要二次点击直接关闭

### ISSUE THREAD

**Issue by Brandzhou** [ganlinte/GKD-subscription#92]
### 请输入 误触/不执行规则 的界面的快照或者生成的快照链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

快照地址 https://i.gkd.li/i/17354753
小白用户，实在不懂编码，搞了半天只弄懂了怎么反馈，希望能够适配一下规则，感谢
![Uploading 1728802914750.png…]()

**Comment by Brandzhou** [comment]
刚才图片没有上传成功
![1728802914750](https://github.com/user-attachments/assets/0f5dea5e-9a55-49eb-9b31-c1f9c96b3958)

**Comment by Brandzhou** [comment]
第一个界面快照 https://i.gkd.li/i/17355000
![1728805602985](https://github.com/user-attachments/assets/c8415912-2660-4b21-a1f6-94fe81ef614d)

**Comment by ganlinte** [comment]
已修复
